<?php

/**
 * @file
 * Contains cove_api.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cove_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cove_api module.
    case 'help.page.cove_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('API Module for PBS&#039;s Cove API') . '</p>';
      return $output;

    default:
  }
}
